export const GenderList = [
  { label: "男", value: "男" },
  { label: "女", value: "女" },
  { label: "その他", value: "その他" },
];

export const CountryList = [
  { label: "🇺🇸 America", value: "America" },
  // { label: "🇦🇺 Australia", value: "Australia" },
  // { label: "🇧🇷 Brazil", value: "Brazil" },
  // { label: "🇨🇦 Canada", value: "Canada" },
  // { label: "🇨🇳 China", value: "China" },
  // { label: "🇩🇰 Denmark", value: "Denmark" },
  // { label: "🇬🇧 England", value: "England" },
  // { label: "🇫🇷 France", value: "France" },
  // { label: "🇩🇪 Germany", value: "Germany" },
  // { label: "🇮🇸 Iceland", value: "Iceland" },
  // { label: "🇮🇳 India", value: "India" },
  // { label: "🇮🇹 Italy", value: "Italy" },
  { label: "🇯🇵 Japan", value: "Japan" },
  // { label: "🇰🇷 Korea", value: "Korea" },
  // { label: "🇲🇾 Malaysia", value: "Malaysia" },
  // { label: "🇲🇽 Mexico", value: "Mexico" },
  // { label: "🇳🇱 Netherlands", value: "Netherlands" },
  // { label: "🇳🇿 new zealand", value: "new zealand" },
  // { label: "🇳🇴 Norway", value: "Norway" },
  // { label: "🇵🇱 Poland", value: "Poland" },
  // { label: "🇵🇭 Philippines", value: "Philippines" },
  // { label: "🇷🇺 Russia", value: "Russia" },
  // { label: "🇿🇦 South Africa", value: "South Africa" },
  // { label: "🇪🇸 Spain", value: "Spain" },
  // { label: "🇸🇪 Sweden", value: "Sweden" },
  // { label: "🇹🇼 Taiwan", value: "Taiwan" },
  // { label: "🇹🇭 Thailand", value: "Thailand" },
  // { label: "🇹🇷 Turkey", value: "Turkey" },
  // { label: "🇺🇦 Ukraine", value: "Ukraine" },
];

export const Languages = [
  // { label: "简体中文", value: "简体中文" },
  { label: "English", value: "English" },
  // { label: "English UK", value: "English UK" },
  { label: "日本語", value: "日本語" },
  // { label: "한국어", value: "한국어" },
  // { label: "Svenska", value: "Svenska" },
  // { label: "ไทย", value: "ไทย" },
  // { label: "Türkçe", value: "Türkçe" },
  // { label: "Українська", value: "Українська" },
  // { label: "Русский", value: "Русский" },
  // { label: "Norsk", value: "Norsk" },
  // { label: "Italiano", value: "Italiano" },
  // { label: "Deutsch", value: "Deutsch" },
  // { label: "Français", value: "Français" },
  // { label: "Suomi", value: "Suomi" },
  // { label: "Dansk", value: "Dansk" },
];

export const InfoSelectList = [
  {
    title: "性別",
    state: "gender",
    setState: "setGender",
    minWidth: "90",
    map: GenderList,
  },
  {
    title: "国",
    state: "country",
    setState: "setCountry",
    minWidth: "140",
    map: CountryList,
  },
  {
    title: "言語",
    state: "language",
    setState: "setLanguage",
    minWidth: "120",
    map: Languages,
  },
];
